// <auto-generated />
namespace TechCom.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m12));
        
        string IMigrationMetadata.Id
        {
            get { return "201712082138204_m12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
