// <auto-generated />
namespace TechCom.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201712242030410_productValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
